server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    name: order-service
    url: jdbc:mysql://localhost:3306/order_db
    username: shiv
    password: shiv
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect